name: simple_expense_app
description: A simple expense tracker connected to Firebase Firestore.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5          # State management
  firebase_core: ^3.6.0     # Firebase Core
  cloud_firestore: ^5.4.0   # Firestore Database

 
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon/icon.png"
  image_path_android: "assets/app_icon/icon_android.png"
  image_path_ios: "assets/app_icon/icon_ios.png"
  web:
    generate: true
    image_path: "assets/app_icon/icon.png"
    background_color: "#6366F1"
  windows:
    generate: true
    image_path: "assets/app_icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon/icon.png"
